//AUTH TYPES
export const REGISTRATION_SUCCESSFUL= 'REGISTRATION_SUCCESSFUL';
export const REGISTRATION_ERROR= 'REGISTRATION_ERROR';
export const GET_USER= 'GET_USER';
export const LOGIN_SUCCESSFUL= 'LOGIN_SUCCESSFUL';
export const LOGIN_ERROR= 'LOGIN_ERROR';
export const LOGOUT= 'LOGOUT';

//SERVICES TYPES
export const SERVICES_GET = 'SERVICES_GET';
export const SELECT_SERVICE = 'SELECT_SERVICE';
export const DELETE_SERVICE= 'DELETE_SERVICE';
export const SERVICE_ERROR= 'SERVICE_ERROR';
export const SERVICE_SEARCH= 'SERVICE_SEARCH';
export const CLEAR_SERVICES= 'CLEAR_SERVICES';

//TICKET TYPES
export const SERVICE_TICKETS= 'PROJECT_TICKETS';
export const DELETE_TICKET= 'DELETE_TICKET';
export const SELECT_TICKET= 'SELECT_TICKET';
export const EDIT_TICKET= 'EDIT_TICKET';
export const CLEAR_TICKET_SELECTED= 'CLEAR_TICKET_SELECTED';
export const TICKET_ERROR= 'TICKET_ERROR';
export const CLEAR_TICKETS= 'CLEAR_TICKETS';

//ALERT TYPES
export const SHOW_ALERT= 'SHOW_ALERT';
export const HIDE_ALERT= 'HIDE_ALERT';